### ISSUE TITLE
RUN LDpred chromosome by chromosome

### ISSUE THREAD

**Issue by wavefancy** [bvilhjal/ldpred#13]
Hi, 

I had made the LDpred can be run in parallel chromosome by chromosome, this can save the waiting time and also reduce significantly the memory needed, and I also benchmarked the results, it output the same results. Then is there a way I can submit my modification, this may help others.

Here is my code:
https://github.com/wavefancy/WallaceBroad/tree/master/python/LDPred.CHRbyCHR

Wallace

**Comment by biostat0903** [comment]
Hi, 
I also want to do the analysis chromosome by chromosome. Do you have some comments of the problem?

**Comment by carbocation** [comment]
To extend this idea, since LDpred runs within defined windows of adjacent SNPs, wouldn't it be reasonable to chunk the genome into sub-chromosome partitions for the purpose of parallelizing this tool? Or am I missing some place in the code that assesses more distant linkage?

**Comment by bvilhjal** [comment]
Hi Wallace, 

 

I apologise for my extreme lack of response, but I left science (for now) and haven’t maintained LDpred (nor really responded to LDpred emails) for the last couple of years.  I have, however, now decided to try to become a better person 😊 (wrt replying LDpred emails).

 

To do what you want to do, you can make a “pull request” on github, which I´ll then accept. 

 

Best,

Bjarni

**Comment by wavefancy** [comment]
Currently, I broke down the LDpred into two steps, 1) One step is the estimation of the LD structure and also gather data for estimation genome-wide inflation factor. The process is chr by chr. 2) The next step is to do the beta reweight based on the summary data across all of the chrs from step one. 

The minor issue, I changed the scipy.linalg.pinv to numpy.linalg.pinv, I found which is more stable on my version of python, but not guarantee in all situations. 

I think it's better to fork your source and make detail tutorials on how to run chr by chr in order to avoid the contamination of your code base.  

Best, 
Wallace

**Comment by labuve** [comment]
Hello!
Apart from the technical side of the issue, I am also interested in the theoretical part. Currently, my team needs to compute PRS and doing it chromosome-by-chromosome is the most computationally feasible way. However, I have found some articles that claim that LD can span across chromosomes, in which case chromosome-by-chromosome approach might be too restrictive. I was hoping you could share your opinions about this trade off.
Thank you!

**Comment by biostat0903** [comment]
I always ignore the LD structure between different chromosome. Then the calculation burden is low. When I use the ldpred chromosome-by-chromosome, many chromosome will be failed. Because of the genome inflation factor is smaller than 1.

**Comment by wavefancy** [comment]
Hi Sheng,

You can not directly run LDpred chr by chr, just by splitting the input
data, you need to estimate the heritability and inflation factor globally,
which needs twist the code. I am making my code and tutorial public
available in a day or two.

Best regards
Wallace

**Comment by biostat0903** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    Many thanks for you kindly reply and help. 
    
    
         
        
            
    
        font{
            line-height: 1.6;
        }
    

    
        font{
            line-height: 1.6;
        }
    

    
        font{
            line-height: 1.6;
        }
    
Sheng YangPh.D, Postdoctral fellowCenter for Statistical Genetics in Department of BiostatisticsUniversity of MichiganDepartment of BiostatisticsNanjing Medical University



        
    
     

    On 9/26/2018 10:30，wavefancy<notifications@github.com> wrote： 


Hi Sheng,

You can not directly run LDpred chr by chr, just by splitting the input
data, you need to estimate the heritability and inflation factor globally,
which needs twist the code. I am making my code and tutorial public
available in a day or two.

Best regards
Wallace

**Comment by labuve** [comment]
Amazing! Thanks a lot! :)

On 26 Sep 2018, at 20:27, wavefancy <notifications@github.com<mailto:notifications@github.com>> wrote:


Here's the tutorial and my code for run LDpred chr by chr:
https://github.com/wavefancy/WallaceBroad/tree/master/python/LDPred.CHRbyCHR<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fwavefancy%2FWallaceBroad%2Ftree%2Fmaster%2Fpython%2FLDPred.CHRbyCHR&data=02%7C01%7Cnurfatima.jandarova%40eui.eu%7C6d890b247f774b1e328208d623ddb5ea%7Cd3f434ee643c409f94aa6db2f23545ce%7C0%7C0%7C636735832495263932&sdata=%2FEzJGrR2Spkf%2FMEY6GhNZg3g%2F%2Befmie9%2BRgps%2FWSexI%3D&reserved=0>

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbvilhjal%2Fldpred%2Fissues%2F13%23issuecomment-424821292&data=02%7C01%7Cnurfatima.jandarova%40eui.eu%7C6d890b247f774b1e328208d623ddb5ea%7Cd3f434ee643c409f94aa6db2f23545ce%7C0%7C0%7C636735832495263932&sdata=ejj%2BaPyVC68jM3rDyB7UG04aZYLfe5auT2su%2Fw%2BGnUs%3D&reserved=0>, or mute the thread<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAXHNgwo0o3Ys2Pyo3jP2J5zgmVOqA0R4ks5ue8cNgaJpZM4VTo3f&data=02%7C01%7Cnurfatima.jandarova%40eui.eu%7C6d890b247f774b1e328208d623ddb5ea%7Cd3f434ee643c409f94aa6db2f23545ce%7C0%7C0%7C636735832495273937&sdata=DA%2BMuohuKkckXEZFLv9CB3tjffsdSIcfBNlRz6tXhZ8%3D&reserved=0>.

The information transmitted is intended only for the person or entity to which it is addressed and may contain confidential and/or privileged material. Any review, retransmission, dissemination, distribution, forwarding, or other use of, or taking of any action in reliance upon, this information by persons or entities other than the intended recipient is prohibited without the express permission of the sender. If you received this communication in error, please contact the sender and delete the material from any computer.

**Comment by bvilhjal** [comment]
Thanks @wavefancy, I really appreciate it!  I have finally found some time to work on LDpred, and will likely spend some time on making it more suitable for large datasets.

**Comment by bvilhjal** [comment]
Dear @labuve, yes one should ignore LD between chromosomes.  If there is substantial LD between chromosomes, it suggests population or family structure, and the dataset would therefore likely not be a good estimate for local LD (which LDpred uses it for).

**Comment by uqzqiao** [comment]
> Here's the tutorial and my code for run LDpred chr by chr:
> https://github.com/wavefancy/WallaceBroad/tree/master/python/LDPred.CHRbyCHR

Hi wavefancy,

Thanks for your contribution! While I was using your code to run LDpred chr by chr, I met the following issue which I don't know how to deal with it. May I seek your help on this matter? Thanks in advance!
The issue is in step 2, the log file is (take chr1 as an example)

"Note: For maximal accuracy all SNPs with LDpred weights should be included in the validation data set.
If they are a subset of the validation data set, then we suggest recalculate LDpred for the overlapping
 SNPs.

Calculating LD information w. radius 25934
Working on chrom_1
149974 503
Done calculating the LD table and LD score, writing to file: test_ldpred_chr1.gz
Genome-wide average LD score was: 42.6342343766
Traceback (most recent call last):
  File "/home/LDpred2/ldpred/LDpred.getLocalLDFile.CHR.Wallace.V1.py", line 634, in <module>
    main()
  File "/home/LDpred2/ldpred/LDpred.getLocalLDFile.CHR.Wallace.V1.py", line 612, in main
    cPickle.dump(ld_dict, f, protocol=2)
SystemError: error return without exception set
"

I still get the *.gz and *_byFileCache.txt files, but I am not confident whether they can be used in the following steps. Thanks!

**Comment by wavefancy** [comment]
Hi,

I never have this error before. But when I check the code. At this step, it
seems the computing is all done, but there's problem to write out the
results to the files, please check the output file related issues, like
file name, path, does disk full etc.

# can also test your python setup by below code.
import cPickle
local_ld_dict_file="test"
f = gzip.open(local_ld_dict_file, 'wb')
ld_dict = {1:2}
cPickle.dump(ld_dict, f, protocol=2)
f.close()

Best regards
Wallace
