### ISSUE TITLE
LDpred score script

### ISSUE THREAD

**Issue by afrahshafquat** [bvilhjal/ldpred#99]
Hello,
Thanks for creating this! I am trying to compute the final scores for the validation dataset and I have a couple of questions on how the scores are computed:

* For the --pf flag, does the script consider binary phenotypes or continuous phenotypes only?How exactly is this information being used to compute the score or is this just to compute heritabilities downstream?
* Does the LDPred score script consider that the LDpred gibbs/p+t scores that were created were using the --logit model i.e. on OR, rather than effect sizes?
* What exactly does the split-by-chrom flag do? I tried looking this up but couldn't find anything. Is there a resource that explains this?
* Are the --f/--p/--r2 flags just to find the right file or do they affect how the score gets computed?

Thanks so much for your help!

**Comment by afrahshafquat** [comment]
Following up on the second question:
* are the ldpred weights reported through gibbs/p+t from OR (odds ratio) summary stats, just adjusted log OR and so can be treated as additive weights? Just want to make sure I interpret these correctly.

**Comment by bvilhjal** [comment]
I apologize for the slow reply on this.  

Regarding your questions, LDpred assumes converts p-values to z-scores internally, which in case of a binary trait can be thought of some sort of liablity scale.  Hence it can be applied to binary and quantitative traits.  However, it only reports R2 in the score step.

The split-by-chromosome flag allows you to validate in plink files that are partitioned by chromosomes.  This is probably poorly implemented feature, and I should actually just remove it.

The --f/--p/--r2  flags in the score are used to find the files made in the previous step.  They are only necessary if you used non-default values in preceding step.

Lastly, yes P+T uses adjusted log OR, so that they can be added up.

Best,
Bjarni
